Создание компонента «Конструктор пиццы»
htmlacademy-vue/1433977-pizza-1 pull request #1
Opened 2023-03-19 21:26 UTC by v2020

---
:mortar_board: [Создание компонента «Конструктор пиццы»](https://up.htmlacademy.ru/vue/1/user/1433977/tasks/2)

2023-03-20 00:45 UTC, S-le requested changes
Поздравляю тебя с выполнением первого домашнего задания! Ты проделал отличную работу.

Оставил небольшую рекомендацию в комментарии к коду.

Перед сдачей домашнего задания не забывай проверять его на соответствие техническому заданию.

Продолжай в том же духе. Жду следующую домашку.

2023-03-20 00:45 UTC, S-le commented on src/frontend/src/views/Index.vue
> +  mounted() {
Если заглянуть в консоль DevTools браузера, то можно заметить ошибку. Ошибка возникает вследствие того, что в момент получения вычисляемого свойство `getFillingStyle` массив `this.ingredients` пустой. Чтобы это исправить следует заменить хук жизненного цикла `mounted` на `[beforeMount](https://ru.vuejs.org/v2/api/#beforeMount)`.

2023-03-20 00:46 UTC, merged

2023-03-20 11:35 UTC, v2020 commented on src/frontend/src/views/Index.vue
> +  mounted() {
Спасибо. В каких случаях лучше использовать mounted, а в каких beforeMount?


Я предполагаю, что в данном случае лучше добавить проверку на наличие массива ingredients
Так как если мы позднее очистим массив ингредиентов - ошибка в свойстве возникнет снова.

2023-03-20 11:46 UTC, S-le commented on src/frontend/src/views/Index.vue
> +  mounted() {
Про проверку хорошая мысль. Но стоит ли проверять само наличие массива или лучше найденный элемент?

Про хуки. Вот [ссылка на урок](https://up.htmlacademy.ru/vue/1/book/1.1.10), там есть диаграмма на которой показано когда и какие хуки вызываются. 
`mounted` вызывается сразу после монтирования компонента. У компонента уже просчитаны все вычисляемые свойства. 
Есть ещё `beforeCreate, created, beforeMount` они вызываются раньше чем `mounted`, но у них есть свои ограничения. Советую еще раз перечитать урок.

2023-03-20 12:43 UTC, v2020 commented on src/frontend/src/views/Index.vue
> +  mounted() {
Спасибо за комментарии.
Согласен, в данном случае вопрос наличия элемента.
Имел в виду лучшие практики.
Например иницилизацию data на основе props лучше всегда проводить в beforeMount, или раньше в created?
Когда рекомендуется использовать mounted и beforeMount? Урок об этом умалчивает :)

2023-03-21 13:50 UTC, S-le commented on src/frontend/src/views/Index.vue
> +  mounted() {
> Например иницилизацию data на основе props лучше всегда проводить в beforeMount, или раньше в created?
Можно проводить в `beforeMount`, а можно и в `created`.

> Когда рекомендуется использовать mounted и beforeMount? Урок об этом умалчивает
Вот [ссылка на документацию](https://ru.vuejs.org/v2/guide/instance.html#%D0%A5%D1%83%D0%BA%D0%B8-%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D1%86%D0%B8%D0%BA%D0%BB%D0%B0-%D1%8D%D0%BA%D0%B7%D0%B5%D0%BC%D0%BF%D0%BB%D1%8F%D1%80%D0%B0). Там информации не больше.

Тут нет каких-то особых рекомендаций. Это просто инструменты. Каждый хук имеет свои преимущества и свои ограничения. Ведь ты понимаешь, что инициализацию `data` на основе `props` делать в хуке `beforeDestroy` так себе идея. Но если необходимо, например, предупредить пользователя перед выходом, что у него есть данные в форме которые он не сохранил, то этот хук отлично подходит. Так что хуки надо запомнить и когда они вызываются, а остальное понимание придет с опытом.

2023-03-21 14:17 UTC, v2020 commented on src/frontend/src/views/Index.vue
> +  mounted() {
Поделитесь пожалуйста опытом из вашей практики, чтобы перенять ваш опыт.
Спасибо

2023-03-21 14:38 UTC, v2020 commented on src/frontend/src/views/Index.vue
> +  mounted() {
Не буду надоедать. Спасибо за обратную связь.